// com.example.signuplogina.modal.Report.kt
package com.example.signuplogina.modal

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class Report(
    var reportId: String = "", // Auto-generated by Firebase push()
    val reporterUserId: String = "",
    val reportedUserId: String = "",
    val bidId: String = "",         // The bid/exchange this report is about (links to ExchangeAgreement)
    val reportReasonTags: List<String> = emptyList(), // Stores the string labels of selected FeedbackTags
    val reportDescription: String? = null,
    val timestamp: Long = System.currentTimeMillis(),
    var status: String = "pending_review", // "pending_review", "resolved_warned", etc.
    var adminNotes: String? = null,
    var adminActionTakenTimestamp: Long = 0L
) : Parcelable {
    constructor() : this(reportId = "") // For Firebase deserialization
}